/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import acceso.a.datos.BomberoData;
import acceso.a.datos.BrigadaData;
import entidades.Bombero;
import entidades.Brigada;
import java.awt.Graphics;
import java.awt.Image;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pc2
 */
public class bomberoview extends javax.swing.JInternalFrame {
private BomberoData bData= new BomberoData();
private Bombero bom=new Bombero();
private BrigadaData brigadaData= new BrigadaData();
private Brigada bri=null;
    /**
     * Creates new form bomberoview
     */
    public bomberoview() {
        initComponents();
        transparenciaBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/fondoSiniestroEsT.png"));
        Image gen= icono.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(gen,0,0,getWidth(),getHeight(),this);

            }

        };
        jLabel2 = new javax.swing.JLabel();
        jtIdbombero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtCodbrigada = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdFechaNac = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtGruposanguineo = new javax.swing.JTextField();
        jtDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtCelular = new javax.swing.JTextField();
        jrEstado = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 574));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1000, 574));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("idBombero");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        jDesktopPane1.add(jtIdbombero, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 149, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Bombero");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, -1));
        jDesktopPane1.add(jtCodbrigada, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Nombre ");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jDesktopPane1.add(jdFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 160, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Celular");
        jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        jDesktopPane1.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 149, -1));
        jDesktopPane1.add(jtGruposanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 149, -1));
        jDesktopPane1.add(jtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 149, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Apellido");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        jDesktopPane1.add(jtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 149, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("CodBrigada");
        jDesktopPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Documento");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel8.setText("Fecha de Nacimiento");
        jDesktopPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));
        jDesktopPane1.add(jtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 150, -1));

        jrEstado.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jrEstado.setForeground(new java.awt.Color(255, 255, 255));
        jrEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrEstadoActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jrEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel9.setText("grupo sanguíneo");
        jDesktopPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jbNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas112.png"))); // NOI18N
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 49, 47));

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar123123.png"))); // NOI18N
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 49, 47));

        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar12321.png"))); // NOI18N
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 49, 47));

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar323232.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 49, 47));

        jbSalir.setBackground(new java.awt.Color(204, 204, 204));
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir777777777.png"))); // NOI18N
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 49, 47));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel10.setText("Estado");
        jDesktopPane1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
          try{
        //(12,"Cordoba",LocalDate.of(1980, 04, 25),brigada1,7777,5555,true,"Martinez","a+")
              if (jdFechaNac.getDate()==null) {
                   JOptionPane.showMessageDialog(this,"llene todos los campos");
              }else{
 
        LocalDate fechaN= jdFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int doc=Integer.parseInt(jtDocumento.getText());
        String nomb=jtNombre.getText();
        String ape=jtApellido.getText();
        boolean est=jrEstado.isSelected();
        //int codigoB=Integer.parseInt(jtCodbrigada.getText());
        String grupoS=jtGruposanguineo.getText();
        bri=brigadaData.buscarBrigada(Integer.parseInt(jtCodbrigada.getText()));
        int celular=Integer.parseInt(jtCelular.getText());
        int idBombero=Integer.parseInt(jtIdbombero.getText());        
            if (nomb.isEmpty()|| ape.isEmpty() ) {
                JOptionPane.showMessageDialog(this,"llene todos los campos");
                return ;
            }
            if (bom==null) {
                bom=new Bombero(nomb,fechaN,bri,doc,celular,est,ape,grupoS);
                bData.guardarBombero(bom);
            }else{
                bom.setDni(doc);
                bom.setApellido(ape);
                bom.setNombre(nomb);
                bom.setFechaNac(fechaN);
                bom.setCodBrigada(bri);
                bom.setGrupoSanguineo(grupoS);
                bom.setCelular(celular);
                bData.modificarBombero(bom);
            }
              }
        }catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this,"datos incorrectos 02"+nf);
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
         this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        
        jtDocumento.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
        jdFechaNac.setDate(null);
        jtGruposanguineo.setText("");
        jtCelular.setText("");
        jtIdbombero.setText("");
        jtCodbrigada.setText("");
        bom=null;
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
    if (bom!=null) {
            //adata.eliminarAlumno(alu.getIdAlumno());
            bData.eliminarBombero(bom.getIdBombero());
            bom=null;
            limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(this, "debe seleccionar un Bombero");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        try {
            int code=Integer.parseInt(jtIdbombero.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error ingrese un entro");
        }
        
        try{
            int code=Integer.parseInt(jtIdbombero.getText());
            
            BomberoData buscar =new BomberoData();
            bom=bData.buscarBombero(code);
            
            
                if (bom!=null) {
            
            jtNombre.setText(bom.getNombre());
            jtApellido.setText(bom.getApellido());
            Date date = Date.from(bom.getFechaNac().atStartOfDay(ZoneId.systemDefault()).toInstant());
            jdFechaNac.setDate(date);
            jrEstado.setSelected(bom.isEstado());
            jtCodbrigada.setText(bom.getCodBrigada().getCodBrigada()+"");
            jtCelular.setText(bom.getCelular()+"");
            jtGruposanguineo.setText(bom.getGrupoSanguineo());
            jtDocumento.setText(bom.getDni()+"");
                }else{
                    JOptionPane.showMessageDialog(this, "intenté otra vez");
                }
           
            
        }catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "error al llenar los campos");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jrEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private com.toedter.calendar.JDateChooser jdFechaNac;
    private javax.swing.JRadioButton jrEstado;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCelular;
    private javax.swing.JTextField jtCodbrigada;
    private javax.swing.JTextField jtDocumento;
    private javax.swing.JTextField jtGruposanguineo;
    private javax.swing.JTextField jtIdbombero;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
public void limpiarCampos(){
   jtDocumento.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
        jdFechaNac.setDate(new Date ());
        jtGruposanguineo.setText("");
        jtCelular.setText("");
        jtIdbombero.setText("");
        jtCodbrigada.setText("");
        bom=null;
}
public void transparenciaBotones(){
    jbGuardar.setOpaque(false);
    jbGuardar.setContentAreaFilled(false);
    jbGuardar.setBorderPainted(false);
    jbSalir.setOpaque(false);
    jbSalir.setContentAreaFilled(false);
    jbSalir.setBorderPainted(false);
    jbNuevo.setOpaque(false);
    jbNuevo.setContentAreaFilled(false);
    jbNuevo.setBorderPainted(false);
    jbEliminar.setOpaque(false);
    jbEliminar.setContentAreaFilled(false);
    jbEliminar.setBorderPainted(false);
    jbBuscar.setOpaque(false);
    jbBuscar.setContentAreaFilled(false);
    jbBuscar.setBorderPainted(false);
    jbSalir.setOpaque(false);
    jbSalir.setContentAreaFilled(false);
    jbSalir.setBorderPainted(false);
}
}

