/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import acceso.a.datos.BrigadaData;
import acceso.a.datos.CuartelData;
import entidades.Brigada;
import entidades.Cuartel;
import javax.swing.JOptionPane;

/**
 *
 * @author dario
 */
public class brigadaview extends javax.swing.JInternalFrame {
private BrigadaData adata=new BrigadaData();
private CuartelData cdata=new CuartelData();
private Brigada bri=null;
private Cuartel cua=null;
    /**
    /**
     * Creates new form brigadaviews
     */
    public brigadaview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jtnombre_br = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_nro_cuartel = new javax.swing.JTextField();
        jtcodbrigada = new javax.swing.JTextField();
        jbBuscarBrigada = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbGuardar = new javax.swing.JButton();
        jtespecialidad = new javax.swing.JTextField();
        jbNuevo = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jrestado = new javax.swing.JRadioButton();
        jrlibre = new javax.swing.JRadioButton();

        jLabel6.setText("nombre_brigada");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Brigada");

        jLabel7.setText("nro_Cuartel");

        jLabel2.setText("codBrigada");

        jbBuscarBrigada.setText("Buscar");
        jbBuscarBrigada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarBrigadaActionPerformed(evt);
            }
        });

        jLabel3.setText("especialidad");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jrestado.setText("estado");

        jrlibre.setText("libre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtcodbrigada, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(277, 277, 277))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(44, 44, 44)
                                        .addComponent(jtespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jt_nro_cuartel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtnombre_br, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbNuevo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jrlibre)
                                        .addComponent(jrestado))
                                    .addComponent(jLabel6))
                                .addGap(320, 320, 320)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbBuscarBrigada)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbEliminar)))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtcodbrigada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarBrigada))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtnombre_br, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jt_nro_cuartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jrlibre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrestado)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo)
                    .addComponent(jbEliminar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarBrigadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarBrigadaActionPerformed
        // TODO add your handling code here:
            try{
            int code=Integer.parseInt(jtcodbrigada.getText());
            
            bri=adata.buscarBrigada(code);
            
            
                if (bri!=null) {
            
                    jt_nro_cuartel.setText(bri.getCodCuartel()+"");
                    jtcodbrigada.setText(bri.getCodBrigada()+"");
                    jtespecialidad.setText(bri.getEspecialidad());
                    jtnombre_br.setText(bri.getNombreBr());
                    jrestado.setSelected(bri.isEstado());
                    jrlibre.setSelected(bri.isLibre());

                }else{
                    JOptionPane.showMessageDialog(this, "intenté otra vez");
                }     
                       
        }catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "error al llenar los campos");
        }
        
    }//GEN-LAST:event_jbBuscarBrigadaActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        jt_nro_cuartel.setText("");
        jtcodbrigada.setText("");
        jtespecialidad.setText("");
        jtnombre_br.setText("");        
        bri=null;
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        if (bri!=null) {
            adata.eliminarBrigada(bri.getCodBrigada());
            bri=null;
            limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(this, "debe seleccionar un brigada");
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
         try{
                        
        int doc=Integer.parseInt(jtcodbrigada.getText());
        String nomb=jtnombre_br.getText();
        String espec=jtespecialidad.getText();
        cua = cdata.buscarCuartel(Integer.parseInt(jt_nro_cuartel.getText()));
        boolean est=jrestado.isSelected();
        boolean lib=jrlibre.isSelected();
            if (nomb.isEmpty()|| espec.isEmpty() ) {
                JOptionPane.showMessageDialog(this,"llene todos los campos");
                return ;
            }
            if (bri==null) {
                bri=new Brigada(doc, nomb, espec, lib, nro_cuartel, est);
                adata.guardarBrigada(bri);
            }else{
                bri.setCodBrigada(doc);
                bri.setEspecialidad(espec);
                bri.setNombreBr(nomb);
                bri.setCodCuartel(cua);
                bri.setEstado(est);
                bri.setLibre(lib);
                adata.modificarBrigada(bri);
            }
        }catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this,"datos incorrectos");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbBuscarBrigada;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JRadioButton jrestado;
    private javax.swing.JRadioButton jrlibre;
    private javax.swing.JTextField jt_nro_cuartel;
    private javax.swing.JTextField jtcodbrigada;
    private javax.swing.JTextField jtespecialidad;
    private javax.swing.JTextField jtnombre_br;
    // End of variables declaration//GEN-END:variables

public void limpiarCampos(){
    jt_nro_cuartel.setText("");
    jtcodbrigada.setText("");
    jtespecialidad.setText("");
    jtnombre_br.setText("");
    bri=null;
}


}
