/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import acceso.a.datos.BrigadaData;
import acceso.a.datos.CuartelData;
import entidades.Cuartel;
import java.awt.Graphics;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pc2
 */
public class cuartelview2 extends javax.swing.JInternalFrame {
private CuartelData cdata=new CuartelData();
private BrigadaData brigaData=new BrigadaData();
private Cuartel cua=null;
    /**
     * Creates new form cuartelview2
     */
    public cuartelview2() {
        initComponents();
        transparenciaBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon(getClass().getResource("/imagenes/fondoC2.png"));
        Image gen= icono.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(gen,0,0,getWidth(),getHeight(),this);
            }
        };
        JL_correo = new javax.swing.JLabel();
        JL_telefono = new javax.swing.JLabel();
        JL_coord_Y = new javax.swing.JLabel();
        JL_coord_X = new javax.swing.JLabel();
        JL_direccion = new javax.swing.JLabel();
        JL_nombre_cuartel = new javax.swing.JLabel();
        JL_cod_Cuartel = new javax.swing.JLabel();
        jtCodCuartel = new javax.swing.JTextField();
        jtNombreC = new javax.swing.JTextField();
        jtDireccion = new javax.swing.JTextField();
        jtCoordX = new javax.swing.JTextField();
        jtCoordY = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jrEstado = new javax.swing.JRadioButton();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbListarBon = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setPreferredSize(new java.awt.Dimension(1000, 574));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1000, 574));

        JL_correo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        JL_correo.setText("Correo del Cuartel ");

        JL_telefono.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        JL_telefono.setText("Teléfono del Cuartel");

        JL_coord_Y.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        JL_coord_Y.setText("Coordenada \"Y\"");

        JL_coord_X.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        JL_coord_X.setText("Coordenada \"X\"");

        JL_direccion.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        JL_direccion.setText("Dirección del Cuartel");

        JL_nombre_cuartel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        JL_nombre_cuartel.setText("nombre_cuartel");

        JL_cod_Cuartel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        JL_cod_Cuartel.setText("Buscar x CodCuartel");

        jtCodCuartel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtNombreC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDireccionActionPerformed(evt);
            }
        });

        jtCoordX.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtCoordY.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtCoordY.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jtTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtCorreo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jrEstado.setFont(new java.awt.Font("Arial Black", 0, 11)); // NOI18N
        jrEstado.setText("¿En Funcionamiento? ");

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas112.png"))); // NOI18N
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar123123.png"))); // NOI18N
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar12321.png"))); // NOI18N
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir777777777.png"))); // NOI18N
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Cuartel");

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar323232.png"))); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("Vacío = Cuartel Sin Actividad");

        jbListarBon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/listarBom.jpg"))); // NOI18N
        jbListarBon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarBonActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(JL_correo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JL_telefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JL_coord_Y, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JL_coord_X, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JL_direccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JL_nombre_cuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(JL_cod_Cuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtCodCuartel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtNombreC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtDireccion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtCoordX, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtCoordY, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtTelefono, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jtCorreo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jrEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jbListarBon, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JL_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(JL_nombre_cuartel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(JL_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(JL_coord_X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(JL_coord_Y, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(JL_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jrEstado)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(JL_cod_Cuartel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtCodCuartel)
                                    .addComponent(jtNombreC)
                                    .addComponent(jtDireccion)
                                    .addComponent(jtCoordX)
                                    .addComponent(jtCoordY)
                                    .addComponent(jtTelefono)
                                    .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbListarBon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)))
                .addGap(441, 441, 441))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(JL_cod_Cuartel)
                        .addGap(18, 18, 18)
                        .addComponent(JL_nombre_cuartel)
                        .addGap(18, 18, 18)
                        .addComponent(JL_direccion)
                        .addGap(29, 29, 29)
                        .addComponent(JL_coord_X)
                        .addGap(30, 30, 30)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_coord_Y)
                            .addComponent(jtCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JL_telefono)
                            .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtCodCuartel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbListarBon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_correo)
                    .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jrEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDireccionActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // guardar cuartel
          try{
                        
       
        String nomb=jtNombreC.getText();
        String direc=jtDireccion.getText();
       int coordX = Integer.parseInt(jtCoordX.getText());
       int coordY = Integer.parseInt(jtCoordY.getText());
      // int tel = Integer.parseInt(jtTelefono.getText());
       String correo=jtCorreo.getText();
       boolean est=jrEstado.isSelected();
                String  celular = (jtTelefono.getText());
//                  if (!(celular.matches("[0-9]*") && celular.length()== 10 )){
//                JOptionPane.showMessageDialog(this," El número no es valido  ");
//                return ;
//                }    

                Matcher validar2 = validarTel.matcher(celular);
                String patron = "\\+54 9 \\d{3} \\d{3} \\d{4}";
                Pattern pattern = Pattern.compile(patron);

              // Crear un objeto Matcher para buscar el patron en el texto
               Matcher matcher = pattern.matcher(celular);
                
        
                 if (validar2.matches()|| matcher.matches() ) {
                
                   celular  = validarTel.matcher(celular).replaceAll("+54 9 $2 $3 $4 ");
                 
                 }else{
                 JOptionPane.showMessageDialog(this," El número no es valido  ");
                 return ;
                 }
       
            if (nomb.isEmpty()|| direc.isEmpty() ) {
                JOptionPane.showMessageDialog(this,"llene todos los campos");
                return ;
            }
            if (cua==null) {
                cua=new Cuartel(nomb, direc, coordX,coordY,celular,correo,est);
                cdata.guardarCuartel(cua);
            }else{
                int doc=Integer.parseInt(jtCodCuartel.getText());
                cua.setCodCuartel(doc);
                cua.setDireccion(direc);
                cua.setNombCuartel(nomb);
                cua.setCoorX(coordX);
                cua.setCoorY(coordY);
                cua.setTelefono(celular);
                cua.setCorreo(correo);
                cua.setEstado(est);
                
                cdata.modificarCuartel(cua);
            }
        }catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this,"datos incorrectos"+nf);
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // eliminar cuartel
            if (cua!=null) {
            
            cdata.eliminarCuartel(cua.getCodCuartel());
            cua=null;
            limpiarCampos();
        }else{
            JOptionPane.showMessageDialog(this, "debe seleccionar un cuartel");
        }
      
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // buscar cuartel
         try{
            int code=Integer.parseInt(jtCodCuartel.getText());
            
            cua=cdata.buscarCuartel(code);
            
            
                if (cua!=null) {
            
                    jtNombreC.setText(cua.getNombCuartel());
                    jtCoordX.setText(cua.getCoorX()+"");
                    jtCoordY.setText(cua.getCoorY()+"");
                    jtCorreo.setText(cua.getCorreo());
                    jrEstado.setSelected(cua.isEstado());
                    jtTelefono.setText(cua.getTelefono()+"");
                    jtDireccion.setText(cua.getDireccion());

                }else{
                    JOptionPane.showMessageDialog(this, "intenté otra vez");
                }     
                       
        }catch (NumberFormatException nf){
            JOptionPane.showMessageDialog(this, "error al llenar los campos");
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbListarBonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarBonActionPerformed
        // TODO add your handling code here:
        int cod =Integer.parseInt(jtCodCuartel.getText());//listarBomberosPorBrigada
        JOptionPane.showMessageDialog(this,brigaData.listarBrigadaPorCuartel(cod),"    Brigadas del Cuartel (Nombre Brigada + Especialidad)",JOptionPane.PLAIN_MESSAGE,new ImageIcon("src/imagenes/logoBrigadalis.jpg"));

    }//GEN-LAST:event_jbListarBonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JL_cod_Cuartel;
    private javax.swing.JLabel JL_coord_X;
    private javax.swing.JLabel JL_coord_Y;
    private javax.swing.JLabel JL_correo;
    private javax.swing.JLabel JL_direccion;
    private javax.swing.JLabel JL_nombre_cuartel;
    private javax.swing.JLabel JL_telefono;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbListarBon;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JRadioButton jrEstado;
    private javax.swing.JTextField jtCodCuartel;
    private javax.swing.JTextField jtCoordX;
    private javax.swing.JTextField jtCoordY;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtNombreC;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
public void limpiarCampos(){
    jtCodCuartel.setText("");
    jtCoordX.setText("");
    jtCoordY.setText("");
    jtCorreo.setText("");
    jtDireccion.setText("");
    jtTelefono.setText("");
    jtNombreC.setText("");
    jrEstado.setSelected(false);
    cua=null;
}
public void transparenciaBotones(){
    jbGuardar.setOpaque(false);
    jbGuardar.setContentAreaFilled(false);
    jbGuardar.setBorderPainted(false);
    jbSalir.setOpaque(false);
    jbSalir.setContentAreaFilled(false);
    jbSalir.setBorderPainted(false);
    jbNuevo.setOpaque(false);
    jbNuevo.setContentAreaFilled(false);
    jbNuevo.setBorderPainted(false);
    jbEliminar.setOpaque(false);
    jbEliminar.setContentAreaFilled(false);
    jbEliminar.setBorderPainted(false);
    jbBuscar.setOpaque(false);
    jbBuscar.setContentAreaFilled(false);
    jbBuscar.setBorderPainted(false);
    jbSalir.setOpaque(false);
    jbSalir.setContentAreaFilled(false);
    jbSalir.setBorderPainted(false);
    jbListarBon.setOpaque(false);
    jbListarBon.setContentAreaFilled(false);
    jbListarBon.setBorderPainted(false);
    
}
 private static final Pattern validarTel = 
      Pattern.compile("^(0054|\\+54)?(\\d\\d\\d)-? ?(\\d\\d\\d)-? ?(\\d\\d\\d\\d)$", Pattern.MULTILINE);
}
